import { parseM3U, buildM3U, buildCsv } from './src/m3u.js';
import { STATUS, STATUS_META, scanEntries } from './src/scanner.js';

const $ = id => document.getElementById(id);
const state = { entries: [], results: [], sourceName: '', sourceType: 'file', scanning: false, controller: null, serverAvailable: false };

const el = {
  tabs: [...document.querySelectorAll('.tab')], filePanel: $('fileSource'), urlPanel: $('urlSource'), fileInput: $('fileInput'), dropzone: $('dropzone'), playlistUrl: $('playlistUrl'), loadUrl: $('loadUrl'),
  loadedName: $('loadedName'), entryCount: $('entryCount'), scanMode: $('scanMode'), scanBtn: $('scanBtn'), cancelBtn: $('cancelBtn'), clearBtn: $('clearBtn'), statusText: $('statusText'),
  search: $('search'), statusFilter: $('statusFilter'), groupFilter: $('groupFilter'), concurrency: $('concurrency'), timeout: $('timeout'), retries: $('retries'), deepHls: $('deepHls'), resultsBody: $('resultsBody'), resultMeta: $('resultMeta'),
  exportM3u: $('exportM3u'), exportCsv: $('exportCsv'), exportJson: $('exportJson'), modeLabel: $('modeLabel'),
  statTotal: $('statTotal'), statOnline: $('statOnline'), statResponds: $('statResponds'), statAttention: $('statAttention'), statErrors: $('statErrors'), statDuplicates: $('statDuplicates')
};

async function detectServer() { try { const r = await fetch('/api/health', { cache: 'no-store' }); state.serverAvailable = r.ok; } catch { state.serverAvailable = false; } el.modeLabel.textContent = state.serverAvailable ? 'Local server mode available' : 'Static browser mode'; el.scanMode.textContent = state.serverAvailable ? 'Hybrid' : 'Browser'; }
function setStatus(message) { el.statusText.textContent = message; }
function resetStats() { for (const node of [el.statTotal,el.statOnline,el.statResponds,el.statAttention,el.statErrors,el.statDuplicates]) node.textContent = '0'; }
function setLoaded(entries, name, sourceType) { state.entries = entries; state.results = []; state.sourceName = name; state.sourceType = sourceType; el.loadedName.textContent = name; el.entryCount.textContent = entries.length; el.scanBtn.disabled = !entries.length; el.resultMeta.textContent = `${entries.length.toLocaleString()} playlist entries loaded`; updateGroups(); render(); resetStats(); }
function updateGroups() { const groups = [...new Set(state.entries.map(e => e.group || 'Uncategorized'))].sort((a,b)=>a.localeCompare(b)); el.groupFilter.innerHTML = '<option value="all">All groups</option>' + groups.map(g => `<option value="${escapeHtml(g)}">${escapeHtml(g)}</option>`).join(''); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function fileFromInput(file) { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = parseM3U(String(reader.result || '')); if (!parsed.entries.length) throw new Error('No channel URLs were found.'); setLoaded(parsed.entries, file.name, 'file'); setStatus(`Loaded ${parsed.entries.length.toLocaleString()} entries.`); } catch (error) { setStatus(error.message); } }; reader.onerror = () => setStatus('Could not read the file.'); reader.readAsText(file); }
async function loadUrl() { const url = el.playlistUrl.value.trim(); if (!url) return setStatus('Enter a playlist URL.'); setStatus('Loading playlist...'); el.loadUrl.disabled = true; try { let parsed; if (state.serverAvailable) { const r = await fetch('/api/playlist',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})}); const data = await r.json(); if (!r.ok) throw new Error(data.error || 'Playlist request failed.'); parsed = data; } else { const r = await fetch(url, { cache:'no-store' }); if (!r.ok) throw new Error(`Playlist returned HTTP ${r.status}.`); parsed = parseM3U(await r.text(), { sourceUrl:url }); } if (!parsed.entries.length) throw new Error('No channel URLs were found.'); setLoaded(parsed.entries, parsed.source || url, 'url'); setStatus(`Loaded ${parsed.entries.length.toLocaleString()} entries.`); } catch (error) { setStatus(error.message || 'Unable to load playlist.'); } finally { el.loadUrl.disabled = false; } }

function passesFilter(result) {
  const q = el.search.value.trim().toLowerCase(); const status = el.statusFilter.value; const group = el.groupFilter.value;
  const haystack = `${result.name} ${result.group} ${result.url} ${result.detail}`.toLowerCase(); if (q && !haystack.includes(q)) return false; if (group !== 'all' && result.group !== group) return false;
  if (status === 'all') return true; if (status === 'attention') return [STATUS.AUTH_REQUIRED,STATUS.FORBIDDEN,STATUS.RATE_LIMITED].includes(result.status); if (status === 'errors') return ![STATUS.ONLINE,STATUS.RESPONDS,STATUS.REACHABLE,STATUS.MANIFEST_ONLY,STATUS.DUPLICATE,STATUS.AUTH_REQUIRED,STATUS.FORBIDDEN,STATUS.RATE_LIMITED].includes(result.status); if (status === 'duplicate') return result.status === STATUS.DUPLICATE; return result.status === status;
}
function visibleResults() { return state.results.filter(passesFilter); }
function render() { const rows = visibleResults(); if (!rows.length) { el.resultsBody.innerHTML = `<tr><td colspan="8" class="empty">${state.results.length ? 'No rows match the current filters.' : 'Load a playlist to begin.'}</td></tr>`; return; } el.resultsBody.innerHTML = rows.map((r,i) => { const meta = STATUS_META[r.status] || STATUS_META[STATUS.UNKNOWN]; return `<tr><td>${r.index+1}</td><td><strong>${escapeHtml(r.name)}</strong>${r.tvgId ? `<div class="details">${escapeHtml(r.tvgId)}</div>`:''}</td><td>${escapeHtml(r.group)}</td><td><span class="status-pill ${meta.tone}">${escapeHtml(meta.label)}</span></td><td>${r.httpStatus ?? '—'}</td><td>${r.latencyMs != null ? `${r.latencyMs} ms` : '—'}</td><td>${escapeHtml(r.confidence)}</td><td><div class="details">${escapeHtml(r.detail)}</div></td></tr>`; }).join(''); }
function updateStats() { const all=state.results; el.statTotal.textContent=all.length; el.statOnline.textContent=all.filter(r=>r.status===STATUS.ONLINE).length; el.statResponds.textContent=all.filter(r=>[STATUS.RESPONDS,STATUS.REACHABLE,STATUS.MANIFEST_ONLY].includes(r.status)).length; el.statAttention.textContent=all.filter(r=>[STATUS.AUTH_REQUIRED,STATUS.FORBIDDEN,STATUS.RATE_LIMITED].includes(r.status)).length; el.statErrors.textContent=all.filter(r=>![STATUS.ONLINE,STATUS.RESPONDS,STATUS.REACHABLE,STATUS.MANIFEST_ONLY,STATUS.DUPLICATE,STATUS.AUTH_REQUIRED,STATUS.FORBIDDEN,STATUS.RATE_LIMITED].includes(r.status)).length; el.statDuplicates.textContent=all.filter(r=>r.status===STATUS.DUPLICATE).length; }
function makeOptions() { return { concurrency:Number(el.concurrency.value), timeoutMs:Number(el.timeout.value), retries:Number(el.retries.value), deepHls:el.deepHls.checked, maxHlsDepth:2 }; }
async function scan() { if (!state.entries.length || state.scanning) return; state.scanning=true; state.results=[]; state.controller=new AbortController(); el.scanBtn.disabled=true; el.cancelBtn.disabled=false; el.exportM3u.disabled=true; el.exportCsv.disabled=true; el.exportJson.disabled=true; setStatus('Scanning...'); const started=performance.now(); try { if (state.serverAvailable) { const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entries:state.entries,options:makeOptions()}),signal:state.controller.signal}); const data=await r.json(); if (!r.ok) throw new Error(data.error || 'Scan failed.'); state.results=data.results; state.serverExports={m3u:data.exportM3U,csv:data.exportCsv}; } else { const scanned=await scanEntries(state.entries,makeOptions(),r=>{state.results.push(r);updateStats();render();},state.controller.signal); state.results=scanned.results; state.serverExports=null; } updateStats(); render(); const elapsed=Math.round(performance.now()-started); el.resultMeta.textContent=`${state.results.length.toLocaleString()} results · ${elapsed} ms`; setStatus(`Scan complete — ${state.results.filter(r=>r.status===STATUS.ONLINE).length.toLocaleString()} online-looking endpoints.`); el.exportM3u.disabled=false; el.exportCsv.disabled=false; el.exportJson.disabled=false; } catch(error) { if (error.name==='AbortError') setStatus('Scan cancelled.'); else setStatus(error.message || 'Scan failed.'); } finally { state.scanning=false; state.controller=null; el.scanBtn.disabled=!state.entries.length; el.cancelBtn.disabled=true; } }
function downloadText(name,text,mime){ const url=URL.createObjectURL(new Blob([text],{type:mime})); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
function exportM3u(){ const online=state.results.filter(r=>r.status===STATUS.ONLINE); downloadText('iptv-online.m3u', state.serverExports?.m3u || buildM3U(online), 'audio/x-mpegurl'); }
function exportCsv(){ downloadText('iptv-scan.csv', state.serverExports?.csv || buildCsv(state.results), 'text/csv'); }
function exportJson(){ downloadText('iptv-scan.json', JSON.stringify({source:state.sourceName, results:state.results}, null, 2), 'application/json'); }
function clearAll(){state.entries=[];state.results=[];state.sourceName='';el.loadedName.textContent='Nothing yet';el.entryCount.textContent='0';el.scanBtn.disabled=true;el.exportM3u.disabled=true;el.exportCsv.disabled=true;el.exportJson.disabled=true;el.resultsBody.innerHTML='<tr><td colspan="8" class="empty">Load a playlist to begin.</td></tr>';el.resultMeta.textContent='No scan performed';el.search.value='';resetStats();setStatus('Ready');}

el.tabs.forEach(tab=>tab.addEventListener('click',()=>{el.tabs.forEach(t=>t.classList.toggle('active',t===tab));const url=tab.dataset.source==='url';el.filePanel.classList.toggle('active',!url);el.urlPanel.classList.toggle('active',url);}));
el.fileInput.addEventListener('change',()=>fileFromInput(el.fileInput.files?.[0]));
el.dropzone.addEventListener('dragover',e=>{e.preventDefault();el.dropzone.style.borderColor='#d9f96a';});el.dropzone.addEventListener('dragleave',()=>el.dropzone.style.borderColor='');el.dropzone.addEventListener('drop',e=>{e.preventDefault();el.dropzone.style.borderColor='';fileFromInput(e.dataTransfer.files?.[0]);});
el.loadUrl.addEventListener('click',loadUrl); el.playlistUrl.addEventListener('keydown',e=>{if(e.key==='Enter')loadUrl();}); el.scanBtn.addEventListener('click',scan); el.cancelBtn.addEventListener('click',()=>state.controller?.abort()); el.clearBtn.addEventListener('click',clearAll); el.exportM3u.addEventListener('click',exportM3u); el.exportCsv.addEventListener('click',exportCsv); el.exportJson.addEventListener('click',exportJson);
['search','statusFilter','groupFilter'].forEach(id=>$(id).addEventListener('input',render));
detectServer();
